version: '3'

services:
  fosmbot:
    build: .
    restart: always
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: fosmbot
      POSTGRES_DB: fosm
      POSTGRES_PASSWORD: mypasswd
      PGDATA: /var/lib/postgresql/data/pgdata
    
    volumes:
      - ./app/db:/var/lib/postgresql/data
